// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelProviderBalanceReadParams = {
/**
 * Provider to read; defaults to the active provider when omitted.
 */
providerId?: string | null, };
