// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of reading the active provider's configured balance endpoint.
 *
 * Lookup failures are reported in `error` instead of failing the request so clients can keep
 * showing the provider row while surfacing that the balance is currently unknown.
 */
export type ModelProviderBalanceReadResponse = {
/**
 * Whether the active provider declares a `balance` endpoint in config.
 */
configured: boolean,
/**
 * Formatted balance value, or `null` when unconfigured or the lookup failed.
 */
value: string | null,
/**
 * Optional currency or unit reported next to the value.
 */
currency: string | null,
/**
 * Optional row label from the provider's `balance` config.
 */
label: string | null,
/**
 * Unix seconds when the lookup completed.
 */
updatedAt: bigint,
/**
 * Non-fatal lookup failure message.
 */
error: string | null, };
